package com.josh.interviewj.interview.support;

import com.josh.interviewj.interview.model.InterviewQuestionKind;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Factory for creating interview question blueprints based on difficulty level.
 *
 * <p>Blueprints define the structure and goals of questions without the actual content.
 * The actual content is generated by LLM or deterministic fallback.</p>
 */
@Component
public class InterviewQuestionBlueprintFactory {

    /**
     * Blueprint for a single interview question.
     */
    public record QuestionBlueprint(
            int sequenceNumber,
            String questionType,
            InterviewQuestionKind questionKind,
            int difficulty,
            int estimatedMinutes,
            String questionGoal,
            String focusHint
    ) {}

    /**
     * Create blueprints based on difficulty level.
     *
     * @param difficultyLevel JUNIOR, MID, or SENIOR
     * @return list of question blueprints
     */
    public List<QuestionBlueprint> createBlueprints(String difficultyLevel) {
        String normalized = normalizeDifficulty(difficultyLevel);

        List<QuestionBlueprint> blueprints = new ArrayList<>();

        // Base 8 questions (common to all levels)
        blueprints.add(new QuestionBlueprint(1, "EXPERIENCE", InterviewQuestionKind.MAIN, 2, 8,
                "Self-introduction or representative project", "Focus on concrete achievements"));
        blueprints.add(new QuestionBlueprint(2, "SKILL", InterviewQuestionKind.MAIN, 3, 10,
                "Core technical fundamentals", "Depth over breadth"));
        blueprints.add(new QuestionBlueprint(3, "SKILL", InterviewQuestionKind.MAIN, 3, 10,
                "Core technical deep dive", "Problem-solving approach"));
        blueprints.add(new QuestionBlueprint(4, "SCENARIO", InterviewQuestionKind.MAIN, 3, 12,
                "Production incident diagnosis", "Systematic troubleshooting"));
        blueprints.add(new QuestionBlueprint(5, "SCENARIO", InterviewQuestionKind.MAIN, 3, 12,
                "Technical trade-offs", "Decision rationale"));
        blueprints.add(new QuestionBlueprint(6, "BEHAVIORAL", InterviewQuestionKind.MAIN, 2, 8,
                "Collaboration and conflict resolution", "Concrete actions and outcomes"));
        blueprints.add(new QuestionBlueprint(7, "EXPERIENCE", InterviewQuestionKind.MAIN, 3, 10,
                "Ownership, impact, and retrospective", "Measurable results"));
        blueprints.add(new QuestionBlueprint(8, "BEHAVIORAL", InterviewQuestionKind.MAIN, 2, 8,
                "Priority, growth, or feedback handling", "Self-awareness"));

        // MID level gets 2 additional questions
        if ("MID".equals(normalized) || "SENIOR".equals(normalized)) {
            blueprints.add(new QuestionBlueprint(9, "SCENARIO", InterviewQuestionKind.MAIN, 4, 15,
                    "Complex requirement breakdown or system design", "Architecture thinking"));
            blueprints.add(new QuestionBlueprint(10, "SKILL", InterviewQuestionKind.MAIN, 3, 10,
                    "Quality, performance, or security", "Best practices awareness"));
        }

        // SENIOR level gets 2 more questions
        if ("SENIOR".equals(normalized)) {
            blueprints.add(new QuestionBlueprint(11, "EXPERIENCE", InterviewQuestionKind.MAIN, 4, 12,
                    "Influence, mentoring, or cross-team collaboration", "Leadership evidence"));
            blueprints.add(new QuestionBlueprint(12, "SCENARIO", InterviewQuestionKind.MAIN, 4, 15,
                    "Architecture evolution, risk control, or failure recovery", "Strategic thinking"));
        }

        return blueprints;
    }

    /**
     * Get the expected question count for a difficulty level.
     *
     * @param difficultyLevel JUNIOR, MID, or SENIOR
     * @return expected question count
     */
    public int getExpectedQuestionCount(String difficultyLevel) {
        String normalized = normalizeDifficulty(difficultyLevel);
        return switch (normalized) {
            case "JUNIOR" -> 8;
            case "MID" -> 10;
            case "SENIOR" -> 12;
            default -> 8;
        };
    }

    private String normalizeDifficulty(String difficultyLevel) {
        if (difficultyLevel == null || difficultyLevel.isBlank()) {
            return "MID";
        }
        return difficultyLevel.trim().toUpperCase(Locale.ROOT);
    }
}