package com.josh.interviewj.billing.model;

public enum BillingEventType {
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_QUOTA_GRANTED,
    SUBSCRIPTION_QUOTA_EXPIRED,
    CREDIT_PURCHASE_GRANTED,
    PAYMENT_REFUNDED,
    PAYMENT_CHARGEBACK,
    MANUAL_ADJUSTMENT,
    USAGE_DEBIT,
    // Reconciliation events for inventory control
    ACTIVATION_CODE_SUBSCRIPTION_GRANTED,
    ACTIVATION_CODE_CREDIT_GRANTED,
    LEGACY_ORDER_WITHOUT_RESERVATION,
    POST_CUTOVER_ORDER_WITHOUT_RESERVATION
}
