package com.josh.interviewj.knowledgebase.preprocessing.lowsignal;

public enum LowSignalReasonCode {
    PROTECTED_BLOCK_TYPE,
    PROTECTED_ERROR_CODE,
    PROTECTED_PATH_OR_URL,
    PROTECTED_COMMAND,
    PROTECTED_TABLE_LABEL,
    DROP_SEPARATOR_PATTERN,
    DROP_PAGE_NUMBER,
    DROP_TOC_FRAGMENT,
    DROP_REPEATED_FOOTER,
    DROP_LOW_READABILITY,
    WARN_SHORT_FRAGMENT,
    WARN_HIGH_SYMBOL_RATIO,
    WARN_POSSIBLE_APPENDIX_SAMPLE_DATA
}
