package com.josh.interviewj.admin.model;

public enum AdminOperationResourceType {
    CREDIT_POLICY_VERSION,
    USER_CREDIT_POLICY,
    LLM_PROVIDER,
    LLM_MODEL_CATALOG,
    LLM_PRICING_VERSION,
    LLM_ROUTING_POLICY,
    USER_ROLE_FLAGS,
    BILLING_PLAN,
    BILLING_PLAN_VERSION,
    CREDIT_PURCHASE_SKU,
    CREDIT_PURCHASE_SKU_VERSION,
    SUBSCRIPTION_CONTRACT,
    BILLING_RECONCILIATION_CASE,
    BILLING_MANUAL_ADJUSTMENT,
    PAYMENT_ORDER,
    SYSTEM_SETTING,
    LLM_PROMPT_TEMPLATE
}
